#!/usr/bin/env ruby
dir = File.dirname(__FILE__)
root = File.expand_path("#{dir}/..")

require "rubygems"
gem "eventmachine", "0.10.0"
require "js_spec"
JsSpec::Server.run(
  "#{root}/spec/javascripts",
  "#{root}/generators/xmlbuilder/templates/public/javascripts",
  "#{root}/generators/xmlbuilder/templates/public"
)